In [4]:
import sys

print(sys.executable)

import pandas as pd

print(pd.__version__)

c:\Projects\clinical-outcome-prediction\.venv\Scripts\python.exe
3.0.5

In [ ]:
from pathlib import Path
import pandas as pd
DATA_DIR = Path("../data/raw/mimic-iv-clinical-database-demo-2.2")

HOSP_DIR = DATA_DIR / "hosp"
ICU_DIR = DATA_DIR / "icu"

print(HOSP_DIR)
print(ICU_DIR)
print((HOSP_DIR / "patients.csv.gz").exists())
print((HOSP_DIR / "admissions.csv.gz").exists())
print((ICU_DIR / "icustays.csv.gz").exists())

..\data\raw\mimic-iv-clinical-database-demo-2.2\hosp
..\data\raw\mimic-iv-clinical-database-demo-2.2\icu
True
True
True

In [8]:

patients = pd.read_csv(HOSP_DIR / "patients.csv.gz")
admissions = pd.read_csv(HOSP_DIR / "admissions.csv.gz")
icustays = pd.read_csv(ICU_DIR / "icustays.csv.gz")

In [9]:
patients.head()

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10014729      F          21         2125       2011 - 2013         NaN
1    10003400      F          72         2134       2011 - 2013  2137-09-02
2    10002428      F          80         2155       2011 - 2013         NaN
3    10032725      F          38         2143       2011 - 2013  2143-03-30
4    10027445      F          48         2142       2011 - 2013  2146-02-09

In [ ]:
patients.shape

(100, 6)

In [11]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subject_id         100 non-null    int64
 1   gender             100 non-null    str
 2   anchor_age         100 non-null    int64
 3   anchor_year        100 non-null    int64
 4   anchor_year_group  100 non-null    str
 5   dod                31 non-null     str
dtypes: int64(3), str(3)
memory usage: 4.8 KB

In [12]:
patients.describe(include="all")

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
count,1.000000e+02,100,100.00000,100.000000,100,31
unique,NaN,2,NaN,NaN,2,31
top,NaN,M,NaN,NaN,2014 - 2016,2137-09-02
freq,NaN,57,NaN,NaN,57,1
mean,1.001878e+07,NaN,61.75000,2148.680000,NaN,NaN
std,1.115115e+04,NaN,16.16979,25.629008,NaN,NaN
min,1.000003e+07,NaN,21.00000,2110.000000,NaN,NaN
25%,1.000889e+07,NaN,51.75000,2129.000000,NaN,NaN
50%,1.001909e+07,NaN,63.00000,2145.500000,NaN,NaN
75%,1.002550e+07,NaN,72.00000,2172.500000,NaN,NaN
max,1.004002e+07,NaN,91.00000,2201.000000,NaN,NaN

In [13]:
patients.isnull().sum()

subject_id            0
gender                0
anchor_age            0
anchor_year           0
anchor_year_group     0
dod                  69
dtype: int64

In [14]:
admissions.head()

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10004235,24181354,2196-02-24 14:38:00,2196-03-04 14:02:00,NaN,URGENT,P03YMR,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicaid,ENGLISH,SINGLE,BLACK/CAPE VERDEAN,2196-02-24 12:15:00,2196-02-24 17:07:00,0
1,10009628,25926192,2153-09-17 17:08:00,2153-09-25 13:20:00,NaN,URGENT,P41R5N,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,?,MARRIED,HISPANIC/LATINO - PUERTO RICAN,NaN,NaN,0
2,10018081,23983182,2134-08-18 02:02:00,2134-08-23 19:35:00,NaN,URGENT,P233F6,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,WHITE,2134-08-17 16:24:00,2134-08-18 03:15:00,0
3,10006053,22942076,2111-11-13 23:39:00,2111-11-15 17:20:00,2111-11-15 17:20:00,URGENT,P38TI6,TRANSFER FROM HOSPITAL,DIED,Medicaid,ENGLISH,NaN,UNKNOWN,NaN,NaN,1
4,10031404,21606243,2113-08-04 18:46:00,2113-08-06 20:57:00,NaN,URGENT,P07HDB,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,NaN,NaN,0

In [15]:
admissions.shape

(275, 16)

In [16]:
admissions.info()

<class 'pandas.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   subject_id            275 non-null    int64
 1   hadm_id               275 non-null    int64
 2   admittime             275 non-null    str
 3   dischtime             275 non-null    str
 4   deathtime             15 non-null     str
 5   admission_type        275 non-null    str
 6   admit_provider_id     275 non-null    str
 7   admission_location    275 non-null    str
 8   discharge_location    233 non-null    str
 9   insurance             275 non-null    str
 10  language              275 non-null    str
 11  marital_status        263 non-null    str
 12  race                  275 non-null    str
 13  edregtime             182 non-null    str
 14  edouttime             182 non-null    str
 15  hospital_expire_flag  275 non-null    int64
dtypes: int64(3), str(13)
memory usage: 34.5 KB

In [17]:
admissions.describe(include="all")

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
count,2.750000e+02,2.750000e+02,275,275,15,275,275,275,233,275,275,263,275,182,182,275.000000
unique,NaN,NaN,275,275,15,9,170,10,10,3,2,4,14,181,181,NaN
top,NaN,NaN,2196-02-24 14:38:00,2196-03-04 14:02:00,2111-11-15 17:20:00,EW EMER.,P41R5N,EMERGENCY ROOM,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE,2193-08-05 05:04:00,2193-08-05 12:00:00,NaN
freq,NaN,NaN,1,1,1,104,9,134,76,149,255,110,170,2,2,NaN
mean,1.001890e+07,2.513055e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.054545
std,1.212777e+04,2.907533e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.227505
min,1.000003e+07,2.004459e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,1.000787e+07,2.258313e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,1.001808e+07,2.517230e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,1.002626e+07,2.767155e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
max,1.004002e+07,2.997458e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

In [18]:
admissions.isnull().sum()

subject_id                0
hadm_id                   0
admittime                 0
dischtime                 0
deathtime               260
admission_type            0
admit_provider_id         0
admission_location        0
discharge_location       42
insurance                 0
language                  0
marital_status           12
race                      0
edregtime                93
edouttime                93
hospital_expire_flag      0
dtype: int64

In [19]:
icustays.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10018328,23786647,31269608,Neuro Stepdown,Neuro Stepdown,2154-04-24 23:03:44,2154-05-02 15:55:21,7.702512
1,10020187,24104168,37509585,Neuro Surgical Intensive Care Unit (Neuro SICU),Neuro Stepdown,2169-01-15 04:56:00,2169-01-20 15:47:50,5.452662
2,10020187,26842957,32554129,Neuro Intermediate,Neuro Intermediate,2170-02-24 18:18:46,2170-02-25 15:15:26,0.872685
3,10012853,27882036,31338022,Trauma SICU (TSICU),Trauma SICU (TSICU),2176-11-26 02:34:49,2176-11-29 20:58:54,3.766725
4,10020740,25826145,32145159,Trauma SICU (TSICU),Trauma SICU (TSICU),2150-06-03 20:12:32,2150-06-04 21:05:58,1.037106

In [20]:
icustays.shape

(140, 8)

In [21]:
icustays.info()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject_id      140 non-null    int64
 1   hadm_id         140 non-null    int64
 2   stay_id         140 non-null    int64
 3   first_careunit  140 non-null    str
 4   last_careunit   140 non-null    str
 5   intime          140 non-null    str
 6   outtime         140 non-null    str
 7   los             140 non-null    float64
dtypes: float64(1), int64(3), str(4)
memory usage: 8.9 KB

In [22]:
icustays.describe(include="all")

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
count,1.400000e+02,1.400000e+02,1.400000e+02,140,140,140,140,140.000000
unique,NaN,NaN,NaN,9,9,140,140,NaN
top,NaN,NaN,NaN,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2154-04-24 23:03:44,2154-05-02 15:55:21,NaN
freq,NaN,NaN,NaN,29,31,1,1,NaN
mean,1.001856e+07,2.515013e+07,3.510255e+07,NaN,NaN,NaN,NaN,3.679379
std,1.085782e+04,2.929135e+06,2.823925e+06,NaN,NaN,NaN,NaN,3.896354
min,1.000003e+07,2.004459e+07,3.005745e+07,NaN,NaN,NaN,NaN,0.023727
25%,1.000905e+07,2.272480e+07,3.250364e+07,NaN,NaN,NaN,NaN,1.170663
50%,1.001900e+07,2.483705e+07,3.513752e+07,NaN,NaN,NaN,NaN,2.155093
75%,1.002384e+07,2.790758e+07,3.730093e+07,NaN,NaN,NaN,NaN,4.907749
max,1.004002e+07,2.997458e+07,3.988077e+07,NaN,NaN,NaN,NaN,20.528681

In [23]:
icustays.isnull().sum()

subject_id        0
hadm_id           0
stay_id           0
first_careunit    0
last_careunit     0
intime            0
outtime           0
los               0
dtype: int64